# Generated by Django 2.2 on 2020-05-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash_app', '0002_quote_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote_posts',
            old_name='desc',
            new_name='quote',
        ),
        migrations.RemoveField(
            model_name='quote_posts',
            name='quoter',
        ),
    ]
