# Generated by Django 2.2 on 2020-05-17 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash_app', '0003_auto_20200517_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_posts',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_posts', to='quote_dash_app.User'),
        ),
    ]
