# Generated by Django 2.2 on 2020-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash_app', '0004_auto_20200517_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_posts',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
